export const SIGN_IN = {
  START: "SIGN_IN_START",
  SUCCESS: "SIGN_IN_SUCCESS",
  FAILURE: "SIGN_IN_FAILURE",
};

export const FETCH_USER_INFO = {
  START: "FETCH_USER_INFO_START",
  SUCCESS: "FETCH_USER_INFO_SUCCESS",
  FAILURE: "FETCH_USER_INFO_FAILURE",
};

export const CLEAR_AUTH_STATE = "CLEAR_AUTH_STATE";

export const CLEAR_SIGN_IN_STATE = "CLEAR_SIGN_IN_STATE";
