export const CREATE_COMMENT = {
  START: "CREATE_COMMENT_START",
  SUCCESS: "CREATE_COMMENT_SUCCESS",
  FAILURE: "FAILURE",
};

export const LIKE_COMMENT = {
  START: "LIKE_COMMENT_START",
  SUCCESS: "LIKE_COMMENT_SUCCESS",
  FAILURE: "LIKE_COMMENT_FAILURE",
};

export const CREATE_REPLY = {
  START: "CREATE_REPLY_START",
  SUCCESS: "CREATE_REPLY_SUCCESS",
  FAILURE: "CREATE_REPLY_FAILURE",
};
