export const CREATE_COMMENT = {
  START: "CREATE_COMMENT_START",
  SUCCESS: "CREATE_COMMENT_SUCCESS",
  FAILURE: "FAILURE",
};

export const EDIT_COMMENT = {
  START: "EDIT_COMMENT_START",
  SUCCESS: "EDIT_COMMENT_SUCCESS",
  FAILURE: "EDIT_COMMENT_FAILURE",
};

export const DELETE_COMMENT = {
  START: "DELETE_COMMENT_START",
  SUCCESS: "DELETE_COMMENT_SUCCESS",
  FAILURE: "DELETE_COMMENT_FAILURE",
};

export const LIKE_COMMENT = {
  START: "LIKE_COMMENT_START",
  SUCCESS: "LIKE_COMMENT_SUCCESS",
  FAILURE: "LIKE_COMMENT_FAILURE",
};

export const CREATE_REPLY = {
  START: "CREATE_REPLY_START",
  SUCCESS: "CREATE_REPLY_SUCCESS",
  FAILURE: "CREATE_REPLY_FAILURE",
};

export const DELETE_REPLY = {
  START: "DELETE_REPLY_START",
  SUCCESS: "DELETE_REPLY_SUCCESS",
  FAILURE: "DELETE_REPLY_FAILURE",
};
