export const FETCH_POST_LIST = {
  START: "FETCH_POST_LIST_START",
  SUCCESS: "FETCH_POST_LIST_SUCCESS",
  FAILURE: "FETCH_POST_LIST_FAILURE",
};

export const CREATE_POST = {
  START: "CREATE_POST_START",
  SUCCESS: "CREATE_POST_SUCCESS",
  FAILURE: "CREATE_POST_FAILURE",
};
