export const FETCH_POST_LIST = {
  START: 'FETCH_POST_LIST_START',
  SUCCESS: 'FETCH_POST_LIST_SUCCESS',
  FAILURE: 'FETCH_POST_LIST_FAILURE',
};

export const CREATE_POST = {
  START: 'CREATE_POST_START',
  SUCCESS: 'CREATE_POST_SUCCESS',
  FAILURE: 'CREATE_POST_FAILURE',
};

export const UPDATE_POST = {
  START: 'UPDATE_POST_START',
  SUCCESS: 'UPDATE_POST_SUCCESS',
  FAILURE: 'UPDATE_POST_FAILURE',
};

export const DELETE_POST = {
  START: 'DELETE_POST_START',
  SUCCESS: 'DELETE_POST_SUCCESS',
  FAILURE: 'DELETE_POST_FAILURE',
};

export const LIKE_POST = {
  START: 'LIKE_POST_START',
  SUCCESS: 'LIKE_POST_SUCCESS',
  FAILURE: 'LIKE_POST_FAILURE',
};

export const CREATE_COMMENT = {
  START: 'CREATE_COMMENT_START',
  SUCCESS: 'CREATE_COMMENT_SUCCESS',
  FAILURE: 'CREATE_COMMENT_FAILURE',
};

export const FETCH_USER_POST = {
  START: 'FETCH_USER_POST_START',
  SUCCESS: 'FETCH_USER_POST_SUCCESS',
  FAILURE: 'FETCH_USER_POST_FAILURE',
};
