export const FETCH_USER_LIST = {
  START: 'FETCH_USER_LIST_START',
  SUCCESS: 'FETCH_USER_LIST_SUCCESS',
  FAILURE: 'FETCH_USER_LIST_FAILURE',
};

export const SIGN_UP = {
  START: 'SIGN_UP_START',
  SUCCESS: 'SIGN_UP_SUCCESS',
  FAILURE: 'SIGN_UP_FAILURE',
};

export const FETCH_USER = {
  START: 'FETCH_USER_START',
  SUCCESS: 'FETCH_USER_SUCCESS',
  FAILURE: 'FETCH_USER_FAILURE',
};

export const REMOVE_USER = {
  START: 'REMOVE_USER_START',
  SUCCESS: 'REMOVE_USER_SUCCESS',
  FAILURE: 'REMOVE_USER_FAILURE',
};

export const UPDATE_USER = {
  START: 'UPDATE_USER_START',
  SUCCESS: 'UPDATE_USER_SUCCESS',
  FAILURE: 'UPDATE_USER_FAILURE',
};

export const FOLLOW_USER = {
  START: 'FOLLOW_USER_START',
  SUCCESS: 'FOLLOW_USER_SUCCESS',
  FAILURE: 'FOLLOW_USER_FAILURE',
};

export const UN_FOLLOW_USER = {
  START: 'UN_FOLLOW_USER_START',
  SUCCESS: 'UN_FOLLOW_USER_SUCCESS',
  FAILURE: 'UN_FOLLOW_USER_FAILURE',
};

export const CLEAR_SIGN_UP_STATE = 'CLEAR_SIGN_UP_STATE';

export const CLEAR_USER_STATE = 'CLEAR_USER_STATE';
